//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPUCause
    {
        public string Comment { get; set; }
        public Nullable<System.DateTime> RestartTime { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> GPUTypicalCauseId { get; set; }
        public int Id { get; set; }
        public int ReplacedDoc { get; set; }
        public Nullable<int> GPUCauseId { get; set; }
        public string Work { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual GPUTypicalCause Cause { get; set; }
        public virtual GPUCause Replaces { get; set; }
    }
}
