//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WFMModelContainer : DbContext
    {
        public WFMModelContainer()
            : base("name=WFMModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TagTrigger> TagTriggerSet { get; set; }
        public DbSet<GPUTypicalCause> GPUTypicalCauseSet { get; set; }
        public DbSet<Employee> EmployeeSet { get; set; }
        public DbSet<GPUCause> GPUCauseSet { get; set; }
        public DbSet<GPUStop> GPUStopSet { get; set; }
    }
}
